# Generated by Django 5.2.4 on 2026-09-29 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Weekend Meeting', max_length=200)),
                ('saturday', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-saturday'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('period', models.CharField(choices=[('14', '2–4 pm'), ('16', '4–6 pm'), ('18', '6–8 pm')], max_length=2)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='meeting.meeting')),
            ],
            options={
                'ordering': ['day', 'period'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='meeting.meeting')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='meeting.timeslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('meeting', 'day', 'period'), name='unique_meeting_slot'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='one_vote_per_meeting'),
        ),
    ]
